### ISSUE TITLE
无法安装“shd101wyy.crossnote”扩展，因为它与 VS Code 的当前版本(版本 1.38.1)不兼容。

### ISSUE THREAD

**Issue by mingxin-yang** [0xGG/vscode-crossnote#2]

**Comment by shd101wyy** [comment]
@mingxin-yang 你好，你把你的 VSCode 更新下就好了。最低的版本要求是 1.43.0

https://github.com/0xGG/vscode-crossnote/blob/master/package.json#L15

谢谢
