### ISSUE TITLE
Notes not displaying in folders within "Notes" section

### ISSUE THREAD

**Issue by ajaffie** [0xGG/vscode-crossnote#4]
Hi,
My notes are not displaying in the folders under "Notes." They do show in the top-level "Notes" section and in the correct tag folders. I've attached images of the empty folder I expect to have notes, the top-level notes folder, and the view of the folders with notes in them in the file explorer.

![image of empty folder](https://user-images.githubusercontent.com/3987709/79245848-a9cfcd80-7e46-11ea-8eb8-461202137987.png)

![image of notes in top-level "Notes" folder](https://user-images.githubusercontent.com/3987709/79246088-016e3900-7e47-11ea-9082-0cf442b0c03b.png)

![image of vscode explorer](https://user-images.githubusercontent.com/3987709/79246325-31b5d780-7e47-11ea-8f26-f5b7a46e4be0.png)

**Comment by shd101wyy** [comment]
Hi there, I would assume it is because of the backslash “\” in your file path. I only considered “/“ but not “\”. 😂 

For example “2020/04” but not “2020\04”.

I will take a look tomorrow. It’s midnight at my time zone now.

Thanks a lot.

**Comment by ajaffie** [comment]
Perhaps this line? https://github.com/0xGG/vscode-crossnote/blob/7be909dbbb1989b14670432d87e6a90de9374406/src/lib/notebook.ts#L215

**Comment by shd101wyy** [comment]
Hi @ajaffie , the issue should be fixed in version `0.0.4`. Cheers :)

**Comment by ajaffie** [comment]
Confirmed, thanks!
